title: Guy Desdames
description: Guy Desdames est principalement connu dans le cinéma pour sa machine Orphée, qui a révolutionné les pratiques de la postsynchronisation et du doublage mais outre ses qualités de constructeur et de concepteur de systèmes, il est également réalisateur, producteur, comédien, photographe et écrivain.
locale: fr_FR
